Unzip RC file use case
WycliffeAssociates/8woc2018-common pull request #59
Opened 2018-10-18 19:10 UTC by mbr4477

- New UnZipResourceContainer use case to unzip RC into app data directory before importing
- Updated ImportResourceContainer and CreateProject to take advantage of new dao/repo transaction behaviors for faster import/create

2018-10-18 20:21 UTC, sarabiaj commented on src/main/kotlin/org/wycliffeassociates/otter/common/domain/ImportResourceContainer.kt
> +                    }
wrap this in an importZip function

2018-10-18 20:26 UTC, jsarabia commented on src/main/kotlin/org/wycliffeassociates/otter/common/domain/ImportResourceContainer.kt
> +                                    val newTestamentBooks = mutableListOf<RelatedCollection>()
don't hard code bible stuff into importing a resource container

2018-10-18 20:30 UTC, jsarabia requested changes
I'm okay to pull in unzipping a resource container, but not the changes to importing to the database- this needs to be sql anyway, but I don't want anything to be context specific, it needs to be generic to a resource container.

2018-10-25 14:09 UTC, mbr4477 commented
Architecture change

2018-10-25 14:09 UTC, closed without merging